## Prepare Tools

In [1]:
import sys
sys.path.append("../src")   # add src/ to Python path

from data.make_dataset import load_data
import features.build_features as features
import models.train as train

# Scikit-Learn models
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

import importlib
importlib.reload(train)

## Load Processed Data

In [2]:
df = load_data("../data/processed/heart-disease.csv")

In [3]:
df

,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels,target
0,53,1,2,171,0,0,1,147,0,5.3,3,3,1
1,40,1,0,94,229,0,1,115,0,3.7,1,1,0
2,49,1,2,133,142,0,0,202,1,5.0,1,0,0
3,43,1,0,138,295,1,1,153,0,3.2,2,2,1
4,31,1,1,199,0,0,2,136,0,5.3,3,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,48,1,2,139,349,0,2,183,1,5.6,2,2,1
996,47,1,3,143,258,1,1,98,1,5.7,1,0,0
997,69,1,0,156,434,1,0,196,0,1.4,3,1,1
998,45,1,1,186,417,0,1,117,1,5.9,3,2,1
999,25,1,0,158,270,0,0,143,1,4.7,0,0,0

## Get the Data Ready

In [4]:
# Split data into features (X) and target (y)
X, y = features.split_features_target(df)

In [5]:
X

,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels
0,53,1,2,171,0,0,1,147,0,5.3,3,3
1,40,1,0,94,229,0,1,115,0,3.7,1,1
2,49,1,2,133,142,0,0,202,1,5.0,1,0
3,43,1,0,138,295,1,1,153,0,3.2,2,2
4,31,1,1,199,0,0,2,136,0,5.3,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...
995,48,1,2,139,349,0,2,183,1,5.6,2,2
996,47,1,3,143,258,1,1,98,1,5.7,1,0
997,69,1,0,156,434,1,0,196,0,1.4,3,1
998,45,1,1,186,417,0,1,117,1,5.9,3,2
999,25,1,0,158,270,0,0,143,1,4.7,0,0

In [6]:
y

0      1
1      0
2      0
3      1
4      1
      ..
995    1
996    0
997    1
998    1
999    0
Name: target, Length: 1000, dtype: int64

In [7]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train.split_train_test(X, y)

In [8]:
X_train.shape, y_train.shape

((800, 12), (800,))

In [9]:
X_test.shape, y_test.shape

((200, 12), (200,))

## Pick the Models

In [ ]:
# Put the models to test in a dictionary
models = {"Logistic_Regression": LogisticRegression(),
          "KNN": KNeighborsClassifier(),
          "Random_Forest": RandomForestClassifier()}

## Train the Models

In [11]:
train.train_models(models, X_train, y_train)

c:\Users\marie\u_git\heart-disease-detection\env\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(